name=fews.domain-events.cdc
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1

database.hostname=fews-pg
database.port=5432
database.dbname=fews
database.user=postgres
database.password=admin

plugin.name=pgoutput
slot.name=fews_domain_events
slot.drop.on.stop=false
publication.name=fews_domain_events
publication.autocreate.mode=filtered
table.include.list=public[.]DomainEvents
snapshot.mode=initial
topic.prefix=fews-cdc
binary.handling.mode=bytes
tombstones.on.delete=false

transforms=unwrap,extractString,loadActivityToHeader,route
transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.delete.tombstone.handling.mode=drop
transforms.extractString.type=org.apache.kafka.connect.transforms.ExtractField$Key
transforms.extractString.field=DomainEventId
transforms.loadActivityToHeader.type=org.apache.kafka.connect.transforms.HeaderFrom$Value
transforms.loadActivityToHeader.fields=ActivityId
transforms.loadActivityToHeader.headers=activity_id
transforms.loadActivityToHeader.operation=move
transforms.route.type=org.apache.kafka.connect.transforms.RegexRouter
transforms.route.regex=fews-cdc[.]public[.]DomainEvents
transforms.route.replacement=fews.DomainEvents
