bootstrap.servers=fews-kb:29092

listeners=http://0.0.0.0:8083
rest.advertised.host.name=fews-connect
rest.advertised.port=8083

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.file.filename=/kafka/data/connect.offsets
offset.flush.interval.ms=1000

plugin.path=/kafka/connect
